export const ACTION_LABELS = {
  page_view: 'بازدید صفحه',
  'auth.login': 'ورود با رمز',
  'auth.verify_otp': 'ورود با کد',
  'auth.send_otp': 'ارسال کد ورود',
  'auth.register': 'ثبت‌نام',
  'trade.create': 'ثبت معامله',
  'trade.update': 'ویرایش معامله',
  'trade.delete': 'حذف معامله',
  'trade.upload': 'بارگذاری معاملات',
  'backtest.create': 'ثبت بک‌تست',
  'backtest.update': 'ویرایش بک‌تست',
  'backtest.delete': 'حذف بک‌تست',
  'market_reality.create': 'ثبت فرصت بازار',
  'market_reality.update': 'ویرایش فرصت بازار',
  'market_reality.delete': 'حذف فرصت بازار',
  'plan.create': 'ثبت پلن',
  'plan.update': 'ویرایش پلن',
  'plan.delete': 'حذف پلن',
  'challenge.create': 'ایجاد چالش',
  'challenge.update': 'ویرایش چالش',
  'challenge.delete': 'حذف چالش',
  'challenge.join': 'پیوستن به چالش',
  'challenge.moderate': 'تایید/رد چالش',
  'challenge.invite_sms': 'پیامک دعوت چالش',
  'message.create': 'ارسال پیام / پیشنهاد',
  'message.update': 'پاسخ پیام',
  'profile.update': 'ویرایش پروفایل',
  'setup.create': 'ایجاد ستاپ',
  'setup.update': 'ویرایش ستاپ',
  'setup.delete': 'حذف ستاپ',
  'checklist.create': 'چک‌لیست',
  'checklist.update': 'به‌روز چک‌لیست',
  'upload.image': 'آپلود تصویر',
  'admin.users': 'مدیریت کاربر',
  'admin.verify': 'تیک آبی',
  'admin.status': 'فعال/غیرفعال کاربر',
  'admin.reset_password': 'ریست رمز',
  'admin.setups': 'ستاپ استاندارد ادمین',
  'admin.symbols': 'نماد ادمین',
  'admin.demo': 'دیتای دمو',
  'admin.messages': 'پاسخ ادمین',
}

export function getActionLabel(action) {
  if (!action) return '—'
  return ACTION_LABELS[action] || action
}
